/**
 * Removes all generated (gitignored) content files so that subsequent
 * steps run against a clean slate — mirroring a fresh CI checkout.
 *
 * Generated artifacts:
 *  - collect-readmes.ts  → src/content/docs/{04-starter-projects,15-add-ons}/…/README.md
 *  - collect-typedocs.ts → src/content/docs/25-references/01-api/*.md (except README.md)
 */

import { readdir, rm } from 'node:fs/promises';
import { join } from 'node:path';

import { README_MAP } from './readme-manifest.js';

const DOCS_WEBSITE_DIR = join(import.meta.dirname, '..');

// 1. Files generated by collect-readmes.ts
await Promise.all(
	README_MAP.map(async ({ dest }) => {
		const filePath = join(DOCS_WEBSITE_DIR, dest);
		await rm(filePath, { force: true });
		console.log(`  ✗ ${dest}`);
	}),
);

// 2. Files generated by collect-typedocs.ts
const apiDirectory = join(
	DOCS_WEBSITE_DIR,
	'src/content/docs/25-references/01-api',
);
try {
	const files = await readdir(apiDirectory);
	await Promise.all(
		files
			.filter((f) => f !== 'README.md' && f.endsWith('.md'))
			.map(async (f) => {
				await rm(join(apiDirectory, f), { force: true });
				console.log(`  ✗ src/content/docs/25-references/01-api/${f}`);
			}),
	);
} catch {
	/* directory may not exist on first run */
}

console.log('\nCleaned generated docs content.');
