packages:
  - ./packages/gracile
  - ./packages/client
  - ./packages/server

  - ./packages/engine
  - ./packages/cli
  - ./packages/create-gracile

  - ./packages/internal/tsconfigs
  - ./packages/internal/utils

  - ./packages/addons/metadata
  - ./packages/addons/svg
  - ./packages/addons/sitemap
  - ./packages/addons/markdown
  - ./packages/addons/markdown-preset-marked
  # - ./packages/addons/minify
  # - ./packages/addons/minify-html-literals
  - ./integration
  - ./packages/labs/client-router
  - ./packages/labs/css-helpers
  # - integration/__fixtures__/server-express
# catalog:
#   vite: ^5.3.5
#   lit: ^3.1.3
#   '@lit-labs/ssr': ^3.2.2
#   '@lit-labs/ssr-client': ^1.1.7
#   typescript: 5.5.4
#   '@types/node': ^20.14.8
#   picocolors: ^1.0.0
#   c8: ^9.1.0
#   tsx: ^4.7.1
