packages:
  - ./packages/gracile
  - ./packages/client
  - ./packages/server

  - ./packages/engine
  - ./packages/cli
  - ./packages/create-gracile

  - ./packages/internal/tsconfigs
  - ./packages/internal/utils

  - ./packages/addons/metadata
  - ./packages/addons/svg
  - ./packages/addons/sitemap
  - ./packages/addons/markdown
  - ./packages/addons/markdown-preset-marked
  - ./integration
  - ./packages/labs/client-router
  - ./packages/labs/css-helpers
  - ./packages/labs/better-errors

catalog:
  vite: ^7.3.1
  lit: ^3.2.1
  '@lit-labs/ssr': ^4.0.0
  '@lit-labs/ssr-client': ^1.1.8
  picocolors: ^1.1.1
  urlpattern-polyfill: ^10.1.0
  commander: ^14.0.3
  '@commander-js/extra-typings': ^14.0.0
#   picocolors: ^1.0.0
#   c8: ^9.1.0
#   tsx: ^4.7.1
