// ---
// THIS FILE IS AUTO-GENERATED BY WEA (Web Elements Analyzer).
// DO NOT EDIT MANUALLY — your changes will be overwritten.
// ---
interface CustomElements {
	/**
	 * ```jsx
	 * class AsciinemaPlayerHeader extends LitElement (<asciinema-player-header>)
	 * ```
	 * ---
	 */
	'asciinema-player-header': {
		elementClass: HTMLElementTagNameMap['asciinema-player-header'];
		properties: {};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class SearchPopup extends LitElement (<search-popup>)
	 * ```
	 * ---
	 * @property `button` — {`HTMLElement[]`}
	 * @property `isSearchBoxVisible` — {`boolean`}
	 */
	'search-popup': {
		elementClass: HTMLElementTagNameMap['search-popup'];
		properties: {
			button?: HTMLElementTagNameMap['search-popup']['button'];
			isSearchBoxVisible?: HTMLElementTagNameMap['search-popup']['isSearchBoxVisible'];
		};
		attributes: {};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class CopyButton extends LitElement (<copy-button>)
	 * ```
	 * ---
	 * @attribute `text` — {`string`}
	 * @property `label` — {`string`}
	 * @property `labelClicked` — {`string`}
	 * @property `currentLabel` — {`string`}
	 * @property `text` — {`string`}
	 */
	'copy-button': {
		elementClass: HTMLElementTagNameMap['copy-button'];
		properties: {
			label?: HTMLElementTagNameMap['copy-button']['label'];
			labelClicked?: HTMLElementTagNameMap['copy-button']['labelClicked'];
			currentLabel?: HTMLElementTagNameMap['copy-button']['currentLabel'];
			/**
			 * @attribute `text`
			 */
			text?: HTMLElementTagNameMap['copy-button']['text'];
		};
		attributes: {
			/**
			 * @property `text`
			 */
			text?: string;
		};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class IconifyIcon extends LitElement (<i-c>)
	 * ```
	 * ---
	 * @attribute `o` — {`string`} — Name
	 * @attribute `s` — {`string`} — Size
	 * @property `name` — {`string`} — Name
	 * @property `size` — {`string`} — Size
	 */
	'i-c': {
		elementClass: HTMLElementTagNameMap['i-c'];
		properties: {
			/**
			 * @attribute `o`
			 */
			name?: HTMLElementTagNameMap['i-c']['name'];
			/**
			 * @attribute `s`
			 */
			size?: HTMLElementTagNameMap['i-c']['size'];
		};
		attributes: {
			/**
			 * @property `name`
			 */
			o?: string;
			/**
			 * @property `size`
			 */
			s?: string;
		};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
	/**
	 * ```jsx
	 * class UnpicImg extends LitElement (<unpic-img>)
	 * ```
	 * ---
	 * @attribute `src` — {`string`}
	 * @attribute `alt` — {`string`}
	 * @attribute `height` — {`number`}
	 * @attribute `width` — {`number`}
	 * @attribute `priority` — {`boolean`}
	 * @attribute `fetchpriority` — {`"high" | "low"`}
	 * @attribute `loading` — {`"eager" | "lazy"`}
	 * @attribute `decoding` — {`"sync" | "async" | "auto"`}
	 * @attribute `background` — {`string`}
	 * @attribute `objectfit` — {`"contain" | "cover" | "fill" | "none" | "scale-down" | "inherit" | "initial"`}
	 * @attribute `aspectratio` — {`number`}
	 * @attribute `layout` — {`Layout`}
	 * @attribute `breakpoints` — {`number[]`}
	 * @attribute `cdn` — {`ImageCdn`}
	 * @attribute `crossorigin` — {`string`}
	 * @attribute `ismap` — {`boolean`}
	 * @attribute `name` — {`string`}
	 * @attribute `referrerpolicy` — {`string`}
	 * @attribute `sizes` — {`string`}
	 * @attribute `usemap` — {`string`}
	 * @property `src` — {`string`}
	 * @property `alt` — {`string`}
	 * @property `height` — {`number`}
	 * @property `width` — {`number`}
	 * @property `priority` — {`boolean`}
	 * @property `fetchpriority` — {`"high" | "low"`}
	 * @property `loading` — {`"eager" | "lazy"`}
	 * @property `decoding` — {`"sync" | "async" | "auto"`}
	 * @property `background` — {`string`}
	 * @property `objectFit` — {`"contain" | "cover" | "fill" | "none" | "scale-down" | "inherit" | "initial"`}
	 * @property `aspectRatio` — {`number`}
	 * @property `layout` — {`Layout`}
	 * @property `breakpoints` — {`number[]`}
	 * @property `cdn` — {`ImageCdn`}
	 * @property `crossOrigin` — {`string`}
	 * @property `isMap` — {`boolean`}
	 * @property `name` — {`string`}
	 * @property `referrerPolicy` — {`string`}
	 * @property `sizes` — {`string`}
	 * @property `useMap` — {`string`}
	 */
	'unpic-img': {
		elementClass: HTMLElementTagNameMap['unpic-img'];
		properties: {
			/**
			 * @attribute `src`
			 */
			src?: HTMLElementTagNameMap['unpic-img']['src'];
			/**
			 * @attribute `alt`
			 */
			alt?: HTMLElementTagNameMap['unpic-img']['alt'];
			/**
			 * @attribute `height`
			 */
			height?: HTMLElementTagNameMap['unpic-img']['height'];
			/**
			 * @attribute `width`
			 */
			width?: HTMLElementTagNameMap['unpic-img']['width'];
			/**
			 * @attribute `priority`
			 */
			priority?: HTMLElementTagNameMap['unpic-img']['priority'];
			/**
			 * @attribute `fetchpriority`
			 */
			fetchpriority?: HTMLElementTagNameMap['unpic-img']['fetchpriority'];
			/**
			 * @attribute `loading`
			 */
			loading?: HTMLElementTagNameMap['unpic-img']['loading'];
			/**
			 * @attribute `decoding`
			 */
			decoding?: HTMLElementTagNameMap['unpic-img']['decoding'];
			/**
			 * @attribute `background`
			 */
			background?: HTMLElementTagNameMap['unpic-img']['background'];
			/**
			 * @attribute `objectfit`
			 */
			objectFit?: HTMLElementTagNameMap['unpic-img']['objectFit'];
			/**
			 * @attribute `aspectratio`
			 */
			aspectRatio?: HTMLElementTagNameMap['unpic-img']['aspectRatio'];
			/**
			 * @attribute `layout`
			 */
			layout?: HTMLElementTagNameMap['unpic-img']['layout'];
			/**
			 * @attribute `breakpoints`
			 */
			breakpoints?: HTMLElementTagNameMap['unpic-img']['breakpoints'];
			/**
			 * @attribute `cdn`
			 */
			cdn?: HTMLElementTagNameMap['unpic-img']['cdn'];
			/**
			 * @attribute `crossorigin`
			 */
			crossOrigin?: HTMLElementTagNameMap['unpic-img']['crossOrigin'];
			/**
			 * @attribute `ismap`
			 */
			isMap?: HTMLElementTagNameMap['unpic-img']['isMap'];
			/**
			 * @attribute `name`
			 */
			name?: HTMLElementTagNameMap['unpic-img']['name'];
			/**
			 * @attribute `referrerpolicy`
			 */
			referrerPolicy?: HTMLElementTagNameMap['unpic-img']['referrerPolicy'];
			/**
			 * @attribute `sizes`
			 */
			sizes?: HTMLElementTagNameMap['unpic-img']['sizes'];
			/**
			 * @attribute `usemap`
			 */
			useMap?: HTMLElementTagNameMap['unpic-img']['useMap'];
		};
		attributes: {
			/**
			 * @property `src`
			 */
			src?: string;
			/**
			 * @property `alt`
			 */
			alt?: string;
			/**
			 * @property `height`
			 */
			height?: number;
			/**
			 * @property `width`
			 */
			width?: number;
			/**
			 * @property `priority`
			 */
			priority?: boolean;
			/**
			 * @property `fetchpriority`
			 */
			fetchpriority?: 'high' | 'low';
			/**
			 * @property `loading`
			 */
			loading?: 'eager' | 'lazy';
			/**
			 * @property `decoding`
			 */
			decoding?: 'sync' | 'async' | 'auto';
			/**
			 * @property `background`
			 */
			background?: string;
			/**
			 * @property `objectFit`
			 */
			objectfit?:
				| 'contain'
				| 'cover'
				| 'fill'
				| 'none'
				| 'scale-down'
				| 'inherit'
				| 'initial';
			/**
			 * @property `aspectRatio`
			 */
			aspectratio?: number;
			/**
			 * @property `layout`
			 */
			layout?: unknown;
			/**
			 * @property `breakpoints`
			 */
			breakpoints?: unknown;
			/**
			 * @property `cdn`
			 */
			cdn?: unknown;
			/**
			 * @property `crossOrigin`
			 */
			crossorigin?: string;
			/**
			 * @property `isMap`
			 */
			ismap?: boolean;
			/**
			 * @property `name`
			 */
			name?: string;
			/**
			 * @property `referrerPolicy`
			 */
			referrerpolicy?: string;
			/**
			 * @property `sizes`
			 */
			sizes?: string;
			/**
			 * @property `useMap`
			 */
			usemap?: string;
		};
		events: {};
		cssProperties: {};
		cssParts: {};
		cssStates: {};
		slots: {};
	};
}
interface GlobalCss {
	properties: {};
}
export type { CustomElements, GlobalCss };
