// ---
// THIS FILE IS AUTO-GENERATED BY WEA (Web Elements Analyzer).
// DO NOT EDIT MANUALLY — your changes will be overwritten.
// ---
interface TagNameMap {
	'asciinema-player-header': import('./../features/asciinema-player-header.js').AsciinemaPlayerHeader;
	'search-popup': import('./../features/search-popup.js').SearchPopup;
	'copy-button': import('./../lib/copy-button.js').CopyButton;
	'i-c': import('./../lib/iconify-icon.js').IconifyIcon;
	'unpic-img': import('./../lib/unpic-element.js').UnpicImg;
}
interface EventMap {}
declare global {
	interface HTMLElementTagNameMap extends TagNameMap {}
	interface GlobalEventHandlersEventMap extends EventMap {}
}
export type { TagNameMap, EventMap };
